# 高级示例的配置文件
app:
  name: "AdvancedApp"
  version: "2.0.0"
  debug: true
  version_float: 2.0
  features:
    - "api"
    - "websocket"
    - "graphql"
  metadata:
    author: "gconf team"
    license: "MIT"
    homepage: "https://github.com/nicexiaonie/gconf"

server:
  host: "127.0.0.1"
  port: 9090
  read_timeout: "60s"
  write_timeout: "60s"

database:
  driver: "postgresql"
  host: "db.example.com"
  port: 5432
  username: "dbuser"
  password: "dbpassword"
  database: "production"
  max_conns: 200

redis:
  host: "redis.example.com"
  port: 6379
  password: "redis_password"
  db: 1

log:
  level: "debug"
  format: "text"
  output: "file"

